### ISSUE TITLE
Code Regarding

### ISSUE THREAD

**Issue by ghost** [Piano-Walrus/termCalc-app#4]
Can You Please Update your code on github 
this code is some bugs and not working theme section proper
i saw your latest apk on play store and i really appriciate with that.
so please contact me brother.....

**Comment by Piano-Walrus** [comment]
Hi, I've stopped working on this project for the time being. The code on GitHub has MANY bugs, but the version on the Google Play Store is fairly stable so I'd recommend just using that version instead.

**Comment by ghost** [comment]
Yes I know old version have so many bugs but i request you that is there
any chanse to we get new bug free code???
Please brother help me out on this 🙏🙏🙏🙏

**Comment by Piano-Walrus** [comment]
No, sorry. Again, I have stopped working on this project for the time being.

**Comment by ghost** [comment]
We can buy your project or not?
